package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Sunday, 21 April, 2024 2:31:48 PM IST
*/

public interface CalculatorOperations 
{
  double add (double x, double y);
  double subtract (double x, double y);
  double multiply (double x, double y);
  double divide (double x, double y);
  void shutdown ();
} // interface CalculatorOperations
